spring:
  datasource:
    url: jdbc:mysql://localhost/spring_boot?autoReconnect=true
    username: root
    password: lucoo
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:mybatis-config.xml
